# Project information
site_name: Portfolio
site_url: https://imprv-ai.github.io/od-zera-do-ai-portfolio/
site_author: IMPRV.ai dev team and supporters
site_description: >-
  Strona zawierająca zbiór projektów związanych z uczeniem maszynowym, analizą danych i sztuczną inteligencją.
  Wszystkie projekty zostały stworzone przez uczestników kursu "Od zera do AI" organizowanego przez IMPRV.ai i GoToIT.

# Repository
repo_name: imprv-ai/od-zera-do-ai-portfolio
repo_url: https://github.com/imprv-ai/od-zera-do-ai-portfolio

# Configuration
theme:
  name: material
  icon:
    logo: material/library
  palette:
    scheme: default
    primary: 'green'
    accent: 'purple'

nav:
  - Eksploracja danych - półmaraton Wrocław 2023:
    - O projekcie: projekty/eda_wrocław_halfmarathon/index.md
  - Analiza Irysów:
    - O projekcie: projekty/iris/index.md
  - Titanic:
    - O projekcie: projekty/titanic/index.md
    - Historia Przeżywalności i Tajemnice Budowy Statku: projekty/titanic/history_of_survivability_and_secrets_of_shipbuilding/index.md
    - "Wnikliwa Analiza EDA: Odkryj Ukryte Zależności w Twoich Danych": projekty/titanic/in_depth_analysis_eda/index.md

  - Uczestnicy:
    - Natalia Swojak: uczestnicy/natalia_swojak.md
    - Rafał Ney: uczestnicy/rafal_ney.md
