# Project information
site_name: Portfolio
site_url: https://imprv-ai.github.io/od-zera-do-ai-portfolio/
site_author: IMPRV.ai dev team and supporters
site_description: >-
  Strona zawierająca zbiór projektów związanych z uczeniem maszynowym, analizą danych i sztuczną inteligencją.
  Wszystkie projekty zostały stworzone przez uczestników kursu "Od zera do AI" organizowanego przez IMPRV.ai i GoToIT.

# Repository
repo_name: imprv-ai/od-zera-do-ai-portfolio
repo_url: https://github.com/imprv-ai/od-zera-do-ai-portfolio

# Configuration
theme:
  name: material
  icon:
    logo: material/library
  palette:
    scheme: default
    primary: 'green'
    accent: 'purple'

nav:
  - Eksploracja danych - półmaraton Wrocław 2023:
    - O projekcie: projects/eda_wroclaw_halfmarathon/index.md
    - EDA danych z półmaratonu Wrocławskiego 2023 w formie prezentacji: projects/eda_wroclaw_halfmarathon/eda_as_presentation/index.md
    - Dokładna Analiza EDA Danych z Półmaratonu we Wrocławiu 2023: projects/eda_wroclaw_halfmarathon/eda_extensive_with_video_comment/index.md
    - "Tajemnice Wrocławskiego Półmaratonu 2023: Analiza EDA": projects/eda_wroclaw_halfmarathon/eda_with_passion/index.md
    - "Fascynująca Analiza EDA Półmaratonu Wrocławskiego 2023": projects/eda_wroclaw_halfmarathon/eda_edge_cases/index.md
    - "Porównanie Półmaratonu: Edycje 2023 vs 2024": projects/eda_wroclaw_halfmarathon/eda_tomasz_waniek_halfmarathon/index.md

  - Irysy:
    - O projekcie: projects/iris/index.md
    - "Analiza Eksploracyjna Danych (EDA) Zbioru Irysów - Perspektywa Natalii": projects/iris/eda_with_ml_preparation/index.md
    - "Fascynująca Analiza Danych EDA Irysów: Eksploracja Domenowa": projects/iris/eda_with_domain_exploration/index.md
    - "Skrupulatna Analiza Danych EDA zbioru o Irysach" : projects/iris/eda_by_mb/index.md
    - "Analiza Danych EDA Irysów: Eksploracja Domenowa" : projects/iris/eda_by_michal_pecyna/index.md
    - "Fenomenalna Analiza Danych EDA Irysów" : projects/iris/eda_by_andrzej_czarnecki/index.md
    - "Kwiatowa Opowieść: Analiza Irysów dla Amelki" : projects/iris/eda_by_jaroslaw_dziedzinski/index.md

  - Titanic:
    - O projekcie: projects/titanic/index.md
    - Historia Przeżywalności i Tajemnice Budowy Statku: projects/titanic/history_of_survivability_and_secrets_of_shipbuilding/index.md
    - "Wnikliwa Analiza EDA: Odkryj Ukryte Zależności w Twoich Danych": projects/titanic/in_depth_analysis_eda/index.md
    - "Analiza Danych z Titanica: Wiek, Płeć i Szalupy Ratunkowe": projects/titanic/eda_different_approach/index.md
    - "EDA Odkrywanie Pojedynczych Zmiennych": projects/titanic/eda_variables_dependency/index.md
    - "Analiza Danych z Titanica - Odkrycia Grzegorza": projects/titanic/eda_by_grzegorz/index.md
    - "Odkryj Historię na Nowo": projects/titanic/eda_by_grzegorz_jaworucki/index.md
    - "Niesamowite Wizualizacje i Transformacje Danych": projects/titanic/eda_by_jakub_klosinski/index.md
    - "Innowacyjna Analiza Danych z Titanica": projects/titanic/eda_by_artur_porochonski/index.md
    - "Odkrywając Tajemnice Titanica: Analiza Danych i Wizualizacje": projects/titanic/eda_by_patrycja_ptaszek/index.md
    - "Titanic: Co Mówią Dane?": projects/titanic/eda_by_artur_lipinski/index.md
    - "Analiza Danych z Titanica: Odkryj Nowe Perspektywy": projects/titanic/eda_by_marita/index.md

  - Aplikacja do przeglądu wyników ankiety powitalnej:
    - O projekcie: projects/survey_overview_app/index.md
    - Kolor i ujmująca prostota: projects/survey_overview_app/colors_and_simplicity/index.md
    - Analizuj, Łącz, Odkrywaj!: projects/survey_overview_app/analyze_connect_discover/index.md
    - Polowanie na dane - prosty i efektywny sposób eksploracji danych: projects/survey_overview_app/data_hunter/index.md
    - Sedes: projects/survey_overview_app/sedes/index.md
    - Aplikacja do przeglądu wyników ankiet - niezwykłe wizualizacje: projects/survey_overview_app/incredible_visualizations/index.md
    - Aplikacja AI Group Fit: projects/survey_overview_app/group_fit_app_by_jakub_klosinski/index.md
    - Interaktywna aplikacja do analizy wyników ankiety powitalnej: projects/survey_overview_app/interactive_survey_analysis_by_grzegorz_jaworucki/index.md

  - Pomagacz językowy:
    - O projekcie: projects/language_helper_app/index.md
    - Kompletne narzędzie do nauki języków obcych: projects/language_helper_app/complete_approach/index.md

  - Aplikacja do obliczania szacowanego czasu przebiegnięcia półmaratonu:
    - O projekcie: projects/half_marathon_app/index.md
    - Predicting time: projects/half_marathon_app/predicting_time/index.md

  - Własne projekty:
    - Pomocnik dla sklepu spożywczego: projects/own_projects/grocery_store_helper/index.md

  - Uczestnicy:
    - Andrzej: uczestnicy/andrzej.md
    - Dariusz Samól: uczestnicy/dariusz_samol.md
    - Dawid: uczestnicy/dawid.md
    - Grzegorz: uczestnicy/grzegorz.md
    - Grzegorz Czopiński: uczestnicy/grzegorz_czopinski.md
    - Grzegorz Jaworucki: uczestnicy/grzegorz_jaworucki.md
    - Kacper Szaruga: uczestnicy/kacper_szaruga.md
    - Maciej Lubaszka: uczestnicy/maciej_lubaszka.md
    - Natalia Swojak: uczestnicy/natalia_swojak.md
    - Rafał Ney: uczestnicy/rafal_ney.md
    - Patryk: uczestnicy/patryk.md
    - Piotr: uczestnicy/piotr.md
    - Karol Zdańkowski: uczestnicy/karol_zdankowski.md
    - Mariusz: uczestnicy/mariusz.md
    - Michał (MB): uczestnicy/mb.md
    - Michał Pecyna: uczestnicy/michal_pecyna.md
    - Mateusz Nowakowski: uczestnicy/mateusz_nowakowski.md
    - Tomasz Waniek: uczestnicy/tomasz_waniek.md
    - Jakub Kłosiński: uczestnicy/jakub_klosinski.md
    - Artur Porochoński: uczestnicy/artur_porochonski.md
    - Andrzej Czarnecki: uczestnicy/andrzej_czarnecki.md
    - Patrycja Ptaszek: uczestnicy/patrycja_ptaszek.md
    - Hubert Drozda: uczestnicy/hubert_drozda.md
    - Jarosław Dziedziński: uczestnicy/jaroslaw_dziedzinski.md
    - Artur Lipiński: uczestnicy/artur_lipinski.md
    - Marita: uczestnicy/marita.md

  - Aleja Gwiazd: hall_of_fame/index.md