# Project information
site_name: Portfolio
site_url: https://imprv-ai.github.io/od-zera-do-ai-portfolio/
site_author: IMPRV.ai dev team and supporters
site_description: >-
  Strona zawierająca zbiór projektów związanych z uczeniem maszynowym, analizą danych i sztuczną inteligencją.
  Wszystkie projekty zostały stworzone przez uczestników kursu "Od zera do AI" organizowanego przez IMPRV.ai i GoToIT.

# Repository
repo_name: imprv-ai/od-zera-do-ai-portfolio
repo_url: https://github.com/imprv-ai/od-zera-do-ai-portfolio

# Configuration
theme:
  name: material
  icon:
    logo: material/library
  palette:
    scheme: default
    primary: 'green'
    accent: 'purple'

nav:
  - Eksploracja danych - półmaraton Wrocław 2023:
    - O projekcie: projects/eda_wroclaw_halfmarathon/index.md
    - EDA danych z półmaratonu Wrocławskiego 2023 w formie prezentacji: projects/eda_wroclaw_halfmarathon/eda_as_presentation/index.md
    - Dokładna Analiza EDA Danych z Półmaratonu we Wrocławiu 2023: projects/eda_wroclaw_halfmarathon/eda_extensive_with_video_comment/index.md
    - "Tajemnice Wrocławskiego Półmaratonu 2023: Analiza EDA": projects/eda_wroclaw_halfmarathon/eda_with_passion/index.md
    - "Fascynująca Analiza EDA Półmaratonu Wrocławskiego 2023": projects/eda_wroclaw_halfmarathon/eda_edge_cases/index.md

  - Irysy:
    - O projekcie: projects/iris/index.md
    - "Analiza Eksploracyjna Danych (EDA) Zbioru Irysów - Perspektywa Natalii": projects/iris/eda_with_ml_preparation/index.md
    - "Fascynująca Analiza Danych EDA Irysów: Eksploracja Domenowa": projects/iris/eda_with_domain_exploration/index.md

  - Titanic:
    - O projekcie: projects/titanic/index.md
    - Historia Przeżywalności i Tajemnice Budowy Statku: projects/titanic/history_of_survivability_and_secrets_of_shipbuilding/index.md
    - "Wnikliwa Analiza EDA: Odkryj Ukryte Zależności w Twoich Danych": projects/titanic/in_depth_analysis_eda/index.md
    - "Analiza Danych z Titanica: Wiek, Płeć i Szalupy Ratunkowe": projects/titanic/eda_different_approach/index.md
    - "EDA Odkrywanie Pojedynczych Zmiennych": projects/titanic/eda_variables_dependency/index.md
    - "Analiza Danych z Titanica - Odkrycia Grzegorza": projects/titanic/eda_by_grzegorz/index.md

  - Aplikacja do przeglądu wyników ankiety powitalnej:
    - O projekcie: projects/survey_overview_app/index.md
    - Kolor i ujmująca prostota: projects/survey_overview_app/colors_and_simplicity/index.md
    - Analizuj, Łącz, Odkrywaj!: projects/survey_overview_app/analyze_connect_discover/index.md

  - Uczestnicy:
    - Andrzej: uczestnicy/andrzej.md
    - Dariusz Samól: uczestnicy/dariusz_samol.md
    - Dawid: uczestnicy/dawid.md
    - Grzegorz: uczestnicy/grzegorz.md
    - Maciej Lubaszka: uczestnicy/maciej_lubaszka.md
    - Natalia Swojak: uczestnicy/natalia_swojak.md
    - Rafał Ney: uczestnicy/rafal_ney.md
    - Patryk: uczestnicy/patryk.md
    - Karol Zdańkowski: uczestnicy/karol_zdankowski.md
